[[session]]
name = "dotfiles "
path = "~/.dotfiles"
startup_command = "nvim"

[[session]]
name = "config "
path = "~/.config"
startup_command = "nvim"

[[session]]
name = "Viva VM "
path = "~/Documents/Viva"
startup_command = "sh connect_workavd.sh"

