[[session]]
name = "Home"
path = "~"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "nvim"

[[session]]
name = "dotfiles-private"
path = "~/.dotfiles-private"
startup_command = "nvim"

[[session]]
name = "vm"
path = "~"
startup_command = "vm"
 
[[session]]
name = "config"
path = "~/.config"
startup_command = "nvim"

[[session]]
name = "scripts"
path = "~/scripts"
#startup_command = "sh connect_workavd.sh"

[[session]]
name = "gits"
path = "~/Documents/gits"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "vulcan-server"
path = "~"
startup_command = "ssh vulcan@192.168.1.2"
