[colors.bright]
black = "0x565656"
blue = "0x49a4f8"
cyan = "0x99faf2"
green = "0xc0e17d"
magenta = "0xa47de9"
red = "0xec5357"
white = "0xffffff"
yellow = "0xf9da6a"

#[colors.cursor]
#cursor = "0xffffff"
#text = "0xF81CE5"

[colors.dim]
black = "0x31363b"
blue = "0x1b668f"
cyan = "0x186c60"
green = "0x17a262"
magenta = "0x614a73"
red = "0x783228"
white = "0x63686d"
yellow = "0xb65619"

[colors.normal]
black = "0x2e2e2e"
blue = "0x47a0f3"
cyan = "0x64dbed"
green = "0xabe047"
magenta = "0x7b5cb0"
red = "0xeb4129"
white = "0xe5e9f0"
yellow = "0xf6c744"

[colors.primary]
background = "0x101421"
foreground = "0xfffbf6"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
builtin_box_drawing = true
size = 10

[font.glyph_offset]
y = 0

[font.normal]
family = "JetBrainsMono NF"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.9
decorations = "None"
blur = true

[window.padding]
x = 3
y = 3
